language: python
python:
    - "3.6"
install:
    - pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl 
    - pip install -r requirements.txt
    - pip install .

script:
    - ./test/run_test.sh

matrix:
    include:
        - env: LINT_CHECK
          python: "3.6"
          install: pip install flake8
          script: flake8
