language: python
python:
    - "3.5"
    - "3.6"
install:
    - pip install -r requirements.txt
    - pip install .

script:
    - ./test/run_test.sh

matrix:
    include:
        - env: LINT_CHECK
          python: "3.6"
          install: pip install flake8
          script: flake8
