language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp27-cp27m-manylinux1_x86_64.whl; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp35-cp35m-manylinux1_x86_64.whl; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install http://download.pytorch.org/whl/cu75/torch-0.2.0.post1-cp36-cp36m-manylinux1_x86_64.whl; fi
    - pip install -r requirements.txt
    - pip install .

script:
    - ./test/run_test.sh

dist: trusty

matrix:
    include:
        - env: LINT_CHECK
          python: "3.6"
          install: pip install flake8
          script: flake8 --exclude palette.py
